export default {
  homeScreen: 'Home',
  welcomeText: 'Welcome to Bolt',
  loginBtnText: 'Login with phone',
  shopText: 'Shop with us',
  loginScreen: 'Login',
  verifyScreen: 'Verify',
  loadingScreen: 'Loading',
  phone: 'Phone',
  phonePlaceHolder: 'Enter phone number',
  phoneKeyboardType: 'phone-pad',
  otp: 'OTP',
  otpPlaceHolder: 'Enter OTP',
  dashboardScreen: 'Dashboard',
  categories: 'Categories',
  featured: 'Featured',
  bestSell: 'Best Sell',
  checkoutScreen: 'Checkout',
};
